api/urls.py
from django.urls import path, include

from . import views

app_name = "api"

urlpatterns = [
    path("get/<int:pk>", views.get, name="get_by_id"),
    path('complete/<int:pk>', views.complete, name="complete_task"),
]

taskr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('taskr/', include('taskr_app.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

taskr_app/urls.py
from django.urls import path, include

from . import views

app_name = "taskr_app"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>", views.DetailView.as_view(), name="detail")
]

api/models.py
from django.db import models

# Create your models here.

taskr_app/models.py
from datetime import timedelta, datetime
from django.forms import ValidationError
from django.utils import timezone
from django.db import models
from django.contrib import admin
from django.core.validators import RegexValidator, MinValueValidator
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    due_next = models.DateTimeField()
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # This should show/hide the repeat days field
    repeats = models.BooleanField(default=True)
    repeat_days = models.SmallIntegerField(
        default=1, verbose_name="Repeat every _ days", validators=[MinValueValidator(1)])
    complete = models.BooleanField(default=False)

    def is_overdue(self) -> bool:
        return self.due_next < timezone.now()

    def __str__(self) -> str:
        return self.title

    def clean(self, *args, **kwargs):
        # HT: https://stackoverflow.com/a/12188214
        # run the base validation
        super(Task, self).clean(*args, **kwargs)

        # Don't allow dates older than now.
        if self.due_next < timezone.now():
            raise ValidationError(
                'Tasks can only be planned for a future time.')

    # TODO: Use timezone type built into django
    def mark_done(self):
        try:
            if (self.repeats):
                # don't mark as complete, just update the next due date
                self.due_next = datetime.combine(timezone.now().date(), self.due_next.time()) + \
                    timedelta(self.repeat_days)
                return (True, False)
            else:
                # mark as complete
                self.complete = True
                return (True, True)
        except:
            return (False, False)

api/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from taskr_app.models import Task

# Create your views here.


def get(request, pk):
    task = get_object_or_404(Task, id=pk)
    # return JsonResponse({task}, safe=False)
    # return JsonResponse({"foo": "bar"})
    res = {
        "title": task.title,
        "description": task.description,
        "assigned_to": task.assigned_to.username,
        "due_next": task.due_next,
        "is_overdue": task.is_overdue(),
        "is_repeating": task.repeats,
    }
    if not task.repeats:
        res["complete"] = task.complete
    return JsonResponse(res)


def complete(request, pk):
    task = get_object_or_404(Task, id=pk)
    res = task.mark_done()
    task.save()
    if res[0]:
        if res[1]:
            return JsonResponse({"success": True, "complete": True})
        else:
            return JsonResponse({"success": True, "complete": False, "due_next": task.due_next})
    else:
        return JsonResponse({"success": False})

taskr_app/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic

from .models import Task

# Create your views here.


class IndexView(generic.ListView):
    template_name = "taskr_app/index.html"
    context_object_name = "tasks_due_soon_list"

    def get_queryset(self):
        return Task.objects.filter(complete__exact="False").order_by("due_next")


class DetailView(generic.DetailView):
    model = Task
    template_name = "taskr_app/detail.html"
    context_object_name = "task_detail"

    # def get_queryset(self, pkid):
    #     return Task.objects.filter(id=pkid)

taskr_app/templates/taskr_app/detail.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Task - {{ task_detail.title }}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        Task Name: {{ task_detail.title }} </br>
        Task details: {{ task_detail.description }} </br>
        Due: {{ task_detail.due_next }}
        <script src="" async defer></script>
    </body>
</html>

taskr_app/templates/taskr_app/index.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Tasks - Home</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'taskr_app/style/style.css' %}">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <!-- TODO: Remove this, debugging in dev only -->
        {% if tasks_due_soon_list %}
            <ul>
            {% for task in tasks_due_soon_list %}
                <li><a href="{% url 'taskr_app:detail' task.id %}">{{ task.title }}</a></li>
            {% endfor %}
            </ul>
            <div class="calendar-widget" id="calendar">
            </div>
        {% endif %}
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>
        <script src="{% static 'taskr_app/js/script.js' %}"></script>
        <script>
            data = [
            {% for item in tasks_due_soon_list %}
             {eventName: "{{ item.title }}", calendar: "Tasks", color: "orange", date: new moment("{{ item.due_next }}"), ref: "{% url 'taskr_app:detail' item.id %}" },
            {% endfor %}
            ]
            var calendar = new Calendar('#calendar', data);
        </script>
    </body>
</html>